### ISSUE TITLE
Not working anymore

### ISSUE THREAD

**Issue by patricknn** [aminnairi/twitch-coin#1]
It is not collecting anymore.

**Comment by aminnairi** [comment]
Hi @patricknn and thanks for your issue. I look into that in the afternoon when I'll get more time. Thanks for taking the time to fill an issue!

**Comment by aminnairi** [comment]
After a quick investigation, I found that they removed a class from their twitch coin button (which is what I used to search in the Document Object Model of the HTML page for a button to click).

But this won't prevent me from fetching this particular button and this means that this will be a rapid fix.

I'll keep you updated once this has been shipped in a new patch version.

Thanks again a ton for having found this issue. Since I have a little more work I don't watch Twitch anymore (sadly) these times.

**Comment by aminnairi** [comment]
@patricknn I sent the new version for a quick inspection from the Google Chrome Web Store Developer team just now. I'll do the same for the Mozilla Firefox Addons Developer team.

**Comment by aminnairi** [comment]
@patricknn A new version from the Mozilla Addons Store is available for the newly 0.1.1 version. It has been so quick! Chrome Web Store generally takes 1 to 2 days to validate a new version but I'll keep you updated.

If you really want to gather you coins now you can download the Mozilla Addon (I just tested the new 0.1.1 version and it is working great!) from [here](https://addons.mozilla.org/en-US/firefox/addon/twitch-coin/).

**Comment by aminnairi** [comment]
Well, the Chrome Addon has already been published! That has been fast.

Thanks again @patricknn for filling this issue and if you have any more problems with the addon don't hesitate to open a new one.

Take care!

**Comment by patricknn** [comment]
Thank you Amin
